version: '3.5'

services:
  auth:
    restart: on-failure
    build: ./auth
    container_name: auth_cont
    environment:
      - SECRET_KEY=DEEPEST_SERET
      - PORT=6100
      - DB_USERNAME=admin
      - DB_PASSWORD=root
      - DB_HOST=db_auth
      - DB_PORT=6101
      - DB_NAME=postgres
      - TOKEN_LIFETIME=100
    depends_on:
      - db_auth
    networks:
      - internal_net
    volumes:
      - auth_vol:/app/

  db_auth:
    restart: on-failure
    container_name: db_auth_cont
    ports:
      - "6101:6101"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "port=6101"
    networks:
      - internal_net
    volumes:
      - db_auth_vol:/var/lib/postgresql/data/
  
  data:
    restart: on-failure
    build: ./data
    container_name: data_cont
    environment:
      - SECRET_KEY=DEEPEST_SERET
      - PORT=6200
      - DB_USERNAME=admin
      - DB_PASSWORD=root
      - DB_HOST=db_data
      - DB_PORT=6201
      - DB_NAME=postgres
    depends_on:
      - db_data
    networks:
      - internal_net
    volumes:
      - data_vol:/app/

  db_data:
    restart: on-failure
    container_name: db_data_cont
    ports:
      - "6201:6201"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "port=6201"
    networks:
      - internal_net
    volumes:
      - db_data_vol:/var/lib/postgresql/data/

  nginx:
    container_name: nginx_cont
    image: nginx:1.23.1-alpine
    networks:
      - internal_net
    ports:
      - 80:80
    depends_on:
      - auth
      - data
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  db_auth_vol: {}
  db_data_vol: {}
  auth_vol: {}
  data_vol: {}
  
networks: 
  internal_net:
    driver: bridge