name: auth
description: Auth Service
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  conduit: ^4.1.5
  jaguar_jwt: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

